apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: rate-limiter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: cheshta7/rate-api:latest   # ✅ local image
          imagePullPolicy: Always          # ✅ important for Minikube
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: rate-limiter
spec:
  type: NodePort                     # ✅ expose externally
  selector:
    app: api
  ports:
    - port: 8000
      targetPort: 8000              # ✅ REQUIRED
      nodePort: 30008              # ✅ fixed port